name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  release:
    name: Create changelog, build artifacts and publish release
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Set up NodeJs
        uses: actions/setup-node@v4
        with:
          node-version-file: './package.json'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Generate Tag Name
        id: GenTagName
        run: |
          genTag="v${{ github.event.inputs.release_version }}"
          echo "value=$genTag" >> $GITHUB_OUTPUT

      - name: Build webUI
        env:
          VERSION_TAG: ${{ steps.GenTagName.outputs.value }}
        run: |
          yarn ci
          yarn build
          yarn build-zip-with-version-tag
          yarn build-md5

      - name: Create Tag
        run: |
          TAG="${{ steps.GenTagName.outputs.value }}"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git tag $TAG
          git push origin $TAG

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "buildZip/*"
          owner: "ngominhtoan"
          repo: "Suwayomi-WebUI"
          tag: ${{ steps.GenTagName.outputs.value }}
          draft: true
